version: '3'
services:
  front:
    build: 
      context: './frontend'
      dockerfile: 'Dockerfile'
    ports:
      - "5173:5173"
    container_name: 'foodapp-frontend'
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack
    volumes:
      - ./frontend:/app
    depends_on:
      - backend  

  backend:   
    build: 
      context: './backend'
      dockerfile: 'Dockerfile' 
    ports:  
      - "3000:5000"
    container_name: 'foodapp-backend'  
    networks:
      - mern-stack
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    restart: always

  mongo:  
    image: mongo
    ports:
      - "27017:27017"
    container_name: 'foodapp-mongo'
    networks:
      - mern-stack
    volumes:
      - mongoData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: vanshjain
      MONGO_INITDB_ROOT_PASSWORD: vansh%402002
      MONGO_INIT_DATABASE: coursebundler

networks:
  mern-stack:

volumes:
  mongoData: